// Code generated by "enumer -type Role -linecomment -json"; DO NOT EDIT.

package model

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _RoleName = "unknownowneradminmember"

var _RoleIndex = [...]uint8{0, 7, 12, 17, 23}

const _RoleLowerName = "unknownowneradminmember"

func (i Role) String() string {
	if i >= Role(len(_RoleIndex)-1) {
		return fmt.Sprintf("Role(%d)", i)
	}
	return _RoleName[_RoleIndex[i]:_RoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RoleNoOp() {
	var x [1]struct{}
	_ = x[UnknownRole-(0)]
	_ = x[OwnerRole-(1)]
	_ = x[AdminRole-(2)]
	_ = x[MamberRole-(3)]
}

var _RoleValues = []Role{UnknownRole, OwnerRole, AdminRole, MamberRole}

var _RoleNameToValueMap = map[string]Role{
	_RoleName[0:7]:        UnknownRole,
	_RoleLowerName[0:7]:   UnknownRole,
	_RoleName[7:12]:       OwnerRole,
	_RoleLowerName[7:12]:  OwnerRole,
	_RoleName[12:17]:      AdminRole,
	_RoleLowerName[12:17]: AdminRole,
	_RoleName[17:23]:      MamberRole,
	_RoleLowerName[17:23]: MamberRole,
}

var _RoleNames = []string{
	_RoleName[0:7],
	_RoleName[7:12],
	_RoleName[12:17],
	_RoleName[17:23],
}

// RoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RoleString(s string) (Role, error) {
	if val, ok := _RoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Role values", s)
}

// RoleValues returns all values of the enum
func RoleValues() []Role {
	return _RoleValues
}

// RoleStrings returns a slice of all String values of the enum
func RoleStrings() []string {
	strs := make([]string, len(_RoleNames))
	copy(strs, _RoleNames)
	return strs
}

// IsARole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Role) IsARole() bool {
	for _, v := range _RoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Role
func (i Role) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Role
func (i *Role) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Role should be a string, got %s", data)
	}

	var err error
	*i, err = RoleString(s)
	return err
}
