// Code generated by "enumer -type TaskStatus -linecomment -json"; DO NOT EDIT.

package model

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TaskStatusName = "UnknownStatusOpenStatusInProgressStatusInReviewStatusResolvedStatusClosedStatus"

var _TaskStatusIndex = [...]uint8{0, 13, 23, 39, 53, 67, 79}

const _TaskStatusLowerName = "unknownstatusopenstatusinprogressstatusinreviewstatusresolvedstatusclosedstatus"

func (i TaskStatus) String() string {
	if i >= TaskStatus(len(_TaskStatusIndex)-1) {
		return fmt.Sprintf("TaskStatus(%d)", i)
	}
	return _TaskStatusName[_TaskStatusIndex[i]:_TaskStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TaskStatusNoOp() {
	var x [1]struct{}
	_ = x[UnknownStatus-(0)]
	_ = x[OpenStatus-(1)]
	_ = x[InProgressStatus-(2)]
	_ = x[InReviewStatus-(3)]
	_ = x[ResolvedStatus-(4)]
	_ = x[ClosedStatus-(5)]
}

var _TaskStatusValues = []TaskStatus{UnknownStatus, OpenStatus, InProgressStatus, InReviewStatus, ResolvedStatus, ClosedStatus}

var _TaskStatusNameToValueMap = map[string]TaskStatus{
	_TaskStatusName[0:13]:       UnknownStatus,
	_TaskStatusLowerName[0:13]:  UnknownStatus,
	_TaskStatusName[13:23]:      OpenStatus,
	_TaskStatusLowerName[13:23]: OpenStatus,
	_TaskStatusName[23:39]:      InProgressStatus,
	_TaskStatusLowerName[23:39]: InProgressStatus,
	_TaskStatusName[39:53]:      InReviewStatus,
	_TaskStatusLowerName[39:53]: InReviewStatus,
	_TaskStatusName[53:67]:      ResolvedStatus,
	_TaskStatusLowerName[53:67]: ResolvedStatus,
	_TaskStatusName[67:79]:      ClosedStatus,
	_TaskStatusLowerName[67:79]: ClosedStatus,
}

var _TaskStatusNames = []string{
	_TaskStatusName[0:13],
	_TaskStatusName[13:23],
	_TaskStatusName[23:39],
	_TaskStatusName[39:53],
	_TaskStatusName[53:67],
	_TaskStatusName[67:79],
}

// TaskStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TaskStatusString(s string) (TaskStatus, error) {
	if val, ok := _TaskStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TaskStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TaskStatus values", s)
}

// TaskStatusValues returns all values of the enum
func TaskStatusValues() []TaskStatus {
	return _TaskStatusValues
}

// TaskStatusStrings returns a slice of all String values of the enum
func TaskStatusStrings() []string {
	strs := make([]string, len(_TaskStatusNames))
	copy(strs, _TaskStatusNames)
	return strs
}

// IsATaskStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TaskStatus) IsATaskStatus() bool {
	for _, v := range _TaskStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TaskStatus
func (i TaskStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TaskStatus
func (i *TaskStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TaskStatus should be a string, got %s", data)
	}

	var err error
	*i, err = TaskStatusString(s)
	return err
}
