# Not used now!
# Instead DB_PASSWORD is generated on the fly. See Makefile#env-init

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_PASSWORD: "your strong password"
  DB_ROOT_PASSWORD: "your strong password"
  REDIS_PASSWORD: "your strong password"
  AUTH_SECRET: "exactly 32 byte in hex-string"
